<?php
/**** **** **** **** **** **** **** **** **** **** **** **** **** **** **** **** 
 * Developer Notes:
 *     User report on 2014-03-25 that this module is broken
 * 
 * 
 * 
 * Version history:
 *     2009-10-03  2.2 version by Nixi (Jonathan)
 *     2011-xx-xx  migrated to version 2.11.x by ukstevef
 * 
 **** **** **** **** **** **** **** **** **** **** **** **** **** **** **** ****/
class Lokaldelen_SE extends superfecta_base {

    public $description = "http://www.lokaldelen.se - This listings include data from the Swedish lokaldelen.se directory.";
    public $version_requirement = "2.11";

    function get_caller_id($thenumber, $run_param=array()) {

        $caller_id = null;

        if ((!$this->IsValidNumber('SE', $this->thenumber))) {
            $this->DebugPrint("Skipping Source - Not a valid Swedish number: {$this->thenumber}");
        } else {
            $this->DebugPrint("Searching Lokaldelen.se ... ");

            $url = "http://www.lokaldelen.se/navigator/-/$this->thenumber/1/";
            $pattern = "/<a class='fn openPreview'.*>(.*)<\/a>/U";

            if ($this->SearchURL($url, $pattern, $match)) {
                $caller_id = $this->ExtractMatch($match);
            }
        }
        return($caller_id);
    }

}